# coding: utf-8

"""
    LEARNINGWEB REST API

    API for interacting with learning data  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.api_api import ApiApi  # noqa: E501
from swagger_client.rest import ApiException


class TestApiApi(unittest.TestCase):
    """ApiApi unit test stubs"""

    def setUp(self):
        self.api = ApiApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_retrievecourses_not_enrolled_api(self):
        """Test case for retrievecourses_not_enrolled_api

        """
        pass

    def test_retrieveuser_course_details_api(self):
        """Test case for retrieveuser_course_details_api

        """
        pass

    def test_retrieveuser_courses_api(self):
        """Test case for retrieveuser_courses_api

        """
        pass


if __name__ == '__main__':
    unittest.main()
