# Generated by Django 5.1.5 on 2025-03-02 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learningapp', '0002_status_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='organisation',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Teacher', 'Teacher'), ('Student', 'Student')], default='Student', max_length=10),
        ),
    ]
