# Generated by Django 5.1.5 on 2025-03-04 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learningapp', '0004_course_coursestudents_userprofile_courses_enrolled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseweek',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courseweek',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
