# Generated by Django 5.1.5 on 2025-03-09 15:57

import learningapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learningapp', '0005_courseweek_end_date_courseweek_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=learningapp.models.course_image_upload_path),
        ),
    ]
