# Generated by Django 5.1.5 on 2025-03-10 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learningapp', '0007_userprofile_first_name_userprofile_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_image',
        ),
    ]
